// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT-3f91TLyK2C0g3iR5pLZNOMQFnvEono',
    appId: '1:969323596514:web:c9924ea20b91940accacbb',
    messagingSenderId: '969323596514',
    projectId: 'notes-flutter-tutorial-project',
    authDomain: 'notes-flutter-tutorial-project.firebaseapp.com',
    storageBucket: 'notes-flutter-tutorial-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMIcisTNXsXj7uRUbzXsIQUyKY7roVvYQ',
    appId: '1:969323596514:android:6a01269ffc21f888ccacbb',
    messagingSenderId: '969323596514',
    projectId: 'notes-flutter-tutorial-project',
    storageBucket: 'notes-flutter-tutorial-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjdmt3kt9S8yXXDNCq7KTKdj5DeFmaYKo',
    appId: '1:969323596514:ios:74ee0f42cf532a7bccacbb',
    messagingSenderId: '969323596514',
    projectId: 'notes-flutter-tutorial-project',
    storageBucket: 'notes-flutter-tutorial-project.appspot.com',
    iosBundleId: 'com.tutorialnote.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjdmt3kt9S8yXXDNCq7KTKdj5DeFmaYKo',
    appId: '1:969323596514:ios:ab0d3b214021c236ccacbb',
    messagingSenderId: '969323596514',
    projectId: 'notes-flutter-tutorial-project',
    storageBucket: 'notes-flutter-tutorial-project.appspot.com',
    iosBundleId: 'com.tutorialnote.mynotes.RunnerTests',
  );
}
